// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs6ItC7t8YM9z9CmILFs2LBNWxSgyVxvk',
    appId: '1:373124875789:web:343586c55846ffd859b744',
    messagingSenderId: '373124875789',
    projectId: 'lightstep-ee187',
    authDomain: 'lightstep-ee187.firebaseapp.com',
    storageBucket: 'lightstep-ee187.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7S8uvR5J0cacYUepB36o9Znmca4SQdWA',
    appId: '1:373124875789:android:37834ae8f364424559b744',
    messagingSenderId: '373124875789',
    projectId: 'lightstep-ee187',
    storageBucket: 'lightstep-ee187.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs6ItC7t8YM9z9CmILFs2LBNWxSgyVxvk',
    appId: '1:373124875789:web:4ea4f0b1eced9e1059b744',
    messagingSenderId: '373124875789',
    projectId: 'lightstep-ee187',
    authDomain: 'lightstep-ee187.firebaseapp.com',
    storageBucket: 'lightstep-ee187.firebasestorage.app',
  );
}
